export interface Element {
  number: number;
  symbol: string;
  name: string;
  atomic_mass: string;
  category: ElementCategory;
  phase: string;
  electron_configuration: string;
  summary: string;
  xpos: number;
  ypos: number;
}

export type ElementCategory =
  | "alkali metal"
  | "alkaline earth metal"
  | "transition metal"
  | "post-transition metal"
  | "metalloid"
  | "reactive nonmetal"
  | "noble gas"
  | "halogen"
  | "lanthanide"
  | "actinide"
  | "unknown";

export const elements: Element[] = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    atomic_mass: "1.008",
    category: "reactive nonmetal",
    phase: "Gas",
    electron_configuration: "1s1",
    summary: "Hydrogen is the chemical element with the symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element in the periodic table.",
    xpos: 1,
    ypos: 1,
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    atomic_mass: "4.0026",
    category: "noble gas",
    phase: "Gas",
    electron_configuration: "1s2",
    summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.",
    xpos: 18,
    ypos: 1,
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    atomic_mass: "6.94",
    category: "alkali metal",
    phase: "Solid",
    electron_configuration: "[He] 2s1",
    summary: "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.",
    xpos: 1,
    ypos: 2,
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    atomic_mass: "9.0122",
    category: "alkaline earth metal",
    phase: "Solid",
    electron_configuration: "[He] 2s2",
    summary: "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
    xpos: 2,
    ypos: 2,
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    atomic_mass: "10.81",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[He] 2s2 2p1",
    summary: "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.",
    xpos: 13,
    ypos: 2,
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    atomic_mass: "12.011",
    category: "reactive nonmetal",
    phase: "Solid",
    electron_configuration: "[He] 2s2 2p2",
    summary: "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
    xpos: 14,
    ypos: 2,
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    atomic_mass: "14.007",
    category: "reactive nonmetal",
    phase: "Gas",
    electron_configuration: "[He] 2s2 2p3",
    summary: "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
    xpos: 15,
    ypos: 2,
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    atomic_mass: "15.999",
    category: "reactive nonmetal",
    phase: "Gas",
    electron_configuration: "[He] 2s2 2p4",
    summary: "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.",
    xpos: 16,
    ypos: 2,
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    atomic_mass: "18.998",
    category: "reactive nonmetal",
    phase: "Gas",
    electron_configuration: "[He] 2s2 2p5",
    summary: "Fluorine is a chemical element with symbol F and atomic number 9. It is the most electronegative element and is extremely reactive: almost all other elements, including some noble gases, form compounds with fluorine.",
    xpos: 17,
    ypos: 2,
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomic_mass: "20.180",
    category: "noble gas",
    phase: "Gas",
    electron_configuration: "[He] 2s2 2p6",
    summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
    xpos: 18,
    ypos: 2,
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    atomic_mass: "22.990",
    category: "alkali metal",
    phase: "Solid",
    electron_configuration: "[Ne] 3s1",
    summary: "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
    xpos: 1,
    ypos: 3,
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomic_mass: "24.305",
    category: "alkaline earth metal",
    phase: "Solid",
    electron_configuration: "[Ne] 3s2",
    summary: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.",
    xpos: 2,
    ypos: 3,
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminum",
    atomic_mass: "26.982",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Ne] 3s2 3p1",
    summary: "Aluminium is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic and ductile metal in the boron group.",
    xpos: 13,
    ypos: 3,
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    atomic_mass: "28.085",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[Ne] 3s2 3p2",
    summary: "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-gray metallic luster; and it is a tetravalent metalloid and semiconductor.",
    xpos: 14,
    ypos: 3,
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    atomic_mass: "30.974",
    category: "reactive nonmetal",
    phase: "Solid",
    electron_configuration: "[Ne] 3s2 3p3",
    summary: "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but because it is highly reactive, phosphorus is never found as a free element on Earth.",
    xpos: 15,
    ypos: 3,
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    atomic_mass: "32.06",
    category: "reactive nonmetal",
    phase: "Solid",
    electron_configuration: "[Ne] 3s2 3p4",
    summary: "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S8.",
    xpos: 16,
    ypos: 3,
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomic_mass: "35.45",
    category: "reactive nonmetal",
    phase: "Gas",
    electron_configuration: "[Ne] 3s2 3p5",
    summary: "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.",
    xpos: 17,
    ypos: 3,
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomic_mass: "39.948",
    category: "noble gas",
    phase: "Gas",
    electron_configuration: "[Ne] 3s2 3p6",
    summary: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third-most abundant gas in the Earth's atmosphere, at 0.934%.",
    xpos: 18,
    ypos: 3,
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    atomic_mass: "39.098",
    category: "alkali metal",
    phase: "Solid",
    electron_configuration: "[Ar] 4s1",
    summary: "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives. In the periodic table, potassium is one of the alkali metals.",
    xpos: 1,
    ypos: 4,
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    atomic_mass: "40.078",
    category: "alkaline earth metal",
    phase: "Solid",
    electron_configuration: "[Ar] 4s2",
    summary: "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.",
    xpos: 2,
    ypos: 4,
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    atomic_mass: "44.956",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d1 4s2",
    summary: "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare-earth element, together with yttrium and the lanthanides.",
    xpos: 3,
    ypos: 4,
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    atomic_mass: "47.867",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d2 4s2",
    summary: "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength. Titanium is resistant to corrosion in sea water, aqua regia, and chlorine.",
    xpos: 4,
    ypos: 4,
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    atomic_mass: "50.942",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d3 4s2",
    summary: "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, malleable transition metal. The elemental metal is rarely found in nature, but once isolated artificially, the formation of an oxide layer stabilizes the free metal somewhat against further oxidation.",
    xpos: 5,
    ypos: 4,
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    atomic_mass: "51.996",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d5 4s1",
    summary: "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6. It is a steely-grey, lustrous, hard and brittle transition metal.",
    xpos: 6,
    ypos: 4,
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    atomic_mass: "54.938",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d5 4s2",
    summary: "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.",
    xpos: 7,
    ypos: 4,
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    atomic_mass: "55.845",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d6 4s2",
    summary: "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table.",
    xpos: 8,
    ypos: 4,
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    atomic_mass: "58.933",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d7 4s2",
    summary: "Cobalt is a chemical element with symbol Co and atomic number 27. Like iron, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.",
    xpos: 9,
    ypos: 4,
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    atomic_mass: "58.693",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d8 4s2",
    summary: "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile.",
    xpos: 10,
    ypos: 4,
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    atomic_mass: "63.546",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d10 4s1",
    summary: "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
    xpos: 11,
    ypos: 4,
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    atomic_mass: "65.38",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d10 4s2",
    summary: "Zinc is a chemical element with symbol Zn and atomic number 30. Zinc is a slightly brittle metal at room temperature and has a blue-silvery appearance when oxidation is removed.",
    xpos: 12,
    ypos: 4,
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    atomic_mass: "69.723",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d10 4s2 4p1",
    summary: "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium is a soft, silvery blue metal at standard temperature and pressure.",
    xpos: 13,
    ypos: 4,
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    atomic_mass: "72.630",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[Ar] 3d10 4s2 4p2",
    summary: "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard-brittle, grayish-white metalloid in the carbon group, chemically similar to its group neighbors silicon and tin.",
    xpos: 14,
    ypos: 4,
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    atomic_mass: "74.922",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[Ar] 3d10 4s2 4p3",
    summary: "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal.",
    xpos: 15,
    ypos: 4,
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    atomic_mass: "78.971",
    category: "reactive nonmetal",
    phase: "Solid",
    electron_configuration: "[Ar] 3d10 4s2 4p4",
    summary: "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal (more rarely considered a metalloid) with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic.",
    xpos: 16,
    ypos: 4,
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    atomic_mass: "79.904",
    category: "reactive nonmetal",
    phase: "Liquid",
    electron_configuration: "[Ar] 3d10 4s2 4p5",
    summary: "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.",
    xpos: 17,
    ypos: 4,
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomic_mass: "83.798",
    category: "noble gas",
    phase: "Gas",
    electron_configuration: "[Ar] 3d10 4s2 4p6",
    summary: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps.",
    xpos: 18,
    ypos: 4,
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomic_mass: "85.468",
    category: "alkali metal",
    phase: "Solid",
    electron_configuration: "[Kr] 5s1",
    summary: "Rubidium is the chemical element with the symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with an atomic mass of 85.4678. Elemental rubidium is highly reactive, with properties similar to those of other alkali metals, such as very rapid oxidation in air.",
    xpos: 1,
    ypos: 5,
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    atomic_mass: "87.62",
    category: "alkaline earth metal",
    phase: "Solid",
    electron_configuration: "[Kr] 5s2",
    summary: "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically. The metal forms a dark oxide layer when it is exposed to air.",
    xpos: 2,
    ypos: 5,
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    atomic_mass: "88.906",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d1 5s2",
    summary: "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a \"rare-earth element\".",
    xpos: 3,
    ypos: 5,
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomic_mass: "91.224",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d2 5s2",
    summary: "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon, the most important source of zirconium. It is a lustrous, grey-white, strong transition metal that resembles hafnium and, to a lesser extent, titanium.",
    xpos: 4,
    ypos: 5,
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    atomic_mass: "92.906",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d4 5s1",
    summary: "Niobium, formerly known as columbium, is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, crystalline, ductile transition metal, often found in the minerals pyrochlore and columbite.",
    xpos: 5,
    ypos: 5,
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomic_mass: "95.95",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d5 5s1",
    summary: "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores.",
    xpos: 6,
    ypos: 5,
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    atomic_mass: "98",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d5 5s2",
    summary: "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive; none are stable, excluding the fully-ionized state of 97Tc.",
    xpos: 7,
    ypos: 5,
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomic_mass: "101.07",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d7 5s1",
    summary: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals.",
    xpos: 8,
    ypos: 5,
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomic_mass: "102.906",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d8 5s1",
    summary: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal. It is a noble metal and a member of the platinum group.",
    xpos: 9,
    ypos: 5,
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    atomic_mass: "106.42",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10",
    summary: "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston.",
    xpos: 10,
    ypos: 5,
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    atomic_mass: "107.868",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s1",
    summary: "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    xpos: 11,
    ypos: 5,
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomic_mass: "112.414",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s2",
    summary: "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, silvery-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.",
    xpos: 12,
    ypos: 5,
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    atomic_mass: "114.818",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s2 5p1",
    summary: "Indium is a chemical element with symbol In and atomic number 49. Indium is a post-transition metal that makes up 0.21 parts per million of the Earth's crust. Indium is a very soft, malleable and easily fusible metal with a melting point higher than sodium and gallium, but lower than lithium and tin.",
    xpos: 13,
    ypos: 5,
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    atomic_mass: "118.710",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s2 5p2",
    summary: "Tin is a chemical element with symbol Sn and atomic number 50. It is a post-transition metal in the carbon group, group 14. Tin exhibits a chemical similarity to both of its neighbors in group 14, germanium and lead, and has two main oxidation states, +2 and the slightly more stable +4.",
    xpos: 14,
    ypos: 5,
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    atomic_mass: "121.760",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s2 5p3",
    summary: "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were powdered for use as medicine and cosmetics, often known by the Arabic name kohl.",
    xpos: 15,
    ypos: 5,
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    atomic_mass: "127.60",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s2 5p4",
    summary: "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur, all three of which are chalcogens.",
    xpos: 16,
    ypos: 5,
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    atomic_mass: "126.904",
    category: "reactive nonmetal",
    phase: "Solid",
    electron_configuration: "[Kr] 4d10 5s2 5p5",
    summary: "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a semi-lustrous, non-metallic solid at standard conditions that melts to form a deep violet liquid at 114 degrees Celsius, and boils to a violet gas at 184 degrees Celsius.",
    xpos: 17,
    ypos: 5,
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomic_mass: "131.293",
    category: "noble gas",
    phase: "Gas",
    electron_configuration: "[Kr] 4d10 5s2 5p6",
    summary: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in Earth's atmosphere in trace amounts.",
    xpos: 18,
    ypos: 5,
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesium",
    atomic_mass: "132.905",
    category: "alkali metal",
    phase: "Solid",
    electron_configuration: "[Xe] 6s1",
    summary: "Caesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-golden alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.",
    xpos: 1,
    ypos: 6,
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    atomic_mass: "137.327",
    category: "alkaline earth metal",
    phase: "Solid",
    electron_configuration: "[Xe] 6s2",
    summary: "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element.",
    xpos: 2,
    ypos: 6,
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    atomic_mass: "138.905",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 5d1 6s2",
    summary: "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes slowly when exposed to air and is soft enough to be cut with a knife.",
    xpos: 3,
    ypos: 9,
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    atomic_mass: "140.116",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f1 5d1 6s2",
    summary: "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile, and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife.",
    xpos: 4,
    ypos: 9,
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomic_mass: "140.908",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f3 6s2",
    summary: "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is the third member of the lanthanide series and is traditionally considered to be one of the rare-earth metals.",
    xpos: 5,
    ypos: 9,
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomic_mass: "144.242",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f4 6s2",
    summary: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach.",
    xpos: 6,
    ypos: 9,
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    atomic_mass: "145",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f5 6s2",
    summary: "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500–600 grams naturally occurring in Earth's crust at any given time.",
    xpos: 7,
    ypos: 9,
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    atomic_mass: "150.36",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f6 6s2",
    summary: "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air. Being a typical member of the lanthanide series, samarium usually possesses the oxidation state +3.",
    xpos: 8,
    ypos: 9,
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    atomic_mass: "151.964",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f7 6s2",
    summary: "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe. It is a moderately hard, silvery metal which readily oxidizes in air and water.",
    xpos: 9,
    ypos: 9,
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomic_mass: "157.25",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f7 5d1 6s2",
    summary: "Gadolinium is a chemical element with symbol Gd and atomic number 64. Gadolinium is a silvery-white metal when oxidation is removed. It is only slightly malleable and is a ductile rare-earth metal.",
    xpos: 10,
    ypos: 9,
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    atomic_mass: "158.925",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f9 6s2",
    summary: "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife. Terbium is never found in nature as a free element, but it is contained in many minerals, including cerite, gadolinite, monazite, xenotime, and euxenite.",
    xpos: 11,
    ypos: 9,
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomic_mass: "162.500",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f10 6s2",
    summary: "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare-earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime.",
    xpos: 12,
    ypos: 9,
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    atomic_mass: "164.930",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f11 6s2",
    summary: "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare-earth element. Holmium was discovered by Swedish chemist Per Teodor Cleve.",
    xpos: 13,
    ypos: 9,
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    atomic_mass: "167.259",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f12 6s2",
    summary: "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements. It is a lanthanide, a rare earth element, originally found in the gadolinite mine in Ytterby in Sweden, from which it got its name.",
    xpos: 14,
    ypos: 9,
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    atomic_mass: "168.934",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f13 6s2",
    summary: "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds.",
    xpos: 15,
    ypos: 9,
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomic_mass: "173.054",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 6s2",
    summary: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state. However, like the other lanthanides, its most common oxidation state is +3, as in its oxide, halides, and other compounds.",
    xpos: 16,
    ypos: 9,
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomic_mass: "174.966",
    category: "lanthanide",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d1 6s2",
    summary: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air. Lutetium is the last element in the lanthanide series, and it is traditionally counted among the rare earths.",
    xpos: 17,
    ypos: 9,
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomic_mass: "178.49",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d2 6s2",
    summary: "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals. Its existence was predicted by Dmitri Mendeleev in 1869, though it was not identified until 1923, making it the penultimate stable element to be discovered.",
    xpos: 4,
    ypos: 6,
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomic_mass: "180.947",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d3 6s2",
    summary: "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, it is named after Tantalus, a villain from Greek mythology. Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.",
    xpos: 5,
    ypos: 6,
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    atomic_mass: "183.84",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d4 6s2",
    summary: "Tungsten, or wolfram, is a chemical element with symbol W and atomic number 74. Tungsten is a rare metal found naturally on Earth almost exclusively as compounds with other elements. It was identified as a new element in 1781 and first isolated as a metal in 1783.",
    xpos: 6,
    ypos: 6,
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    atomic_mass: "186.207",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d5 6s2",
    summary: "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-grey, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion (ppb), rhenium is one of the rarest elements in the Earth's crust.",
    xpos: 7,
    ypos: 6,
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    atomic_mass: "190.23",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d6 6s2",
    summary: "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores. Osmium is the densest naturally occurring element, with a measured density of 22.59 g/cm3.",
    xpos: 8,
    ypos: 6,
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    atomic_mass: "192.217",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d7 6s2",
    summary: "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is considered the second-densest element (after osmium) with a density of 22.56 g/cm3 as defined by experimental X-ray crystallography.",
    xpos: 9,
    ypos: 6,
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    atomic_mass: "195.084",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d9 6s1",
    summary: "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silvery-white transition metal. Its name is derived from the Spanish term platina, meaning \"little silver\".",
    xpos: 10,
    ypos: 6,
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    atomic_mass: "196.966",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d10 6s1",
    summary: "Gold is a chemical element with symbol Au and atomic number 79, making it one of the higher atomic number elements that occur naturally. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. Chemically, gold is a transition metal and a group 11 element.",
    xpos: 11,
    ypos: 6,
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    atomic_mass: "200.592",
    category: "transition metal",
    phase: "Liquid",
    electron_configuration: "[Xe] 4f14 5d10 6s2",
    summary: "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure; the only other element that is liquid under these conditions is the halogen bromine, though metals such as caesium, gallium, and rubidium melt just above room temperature.",
    xpos: 12,
    ypos: 6,
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    atomic_mass: "204.38",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p1",
    summary: "Thallium is a chemical element with symbol Tl and atomic number 81. It is a gray post-transition metal that is not found free in nature. When isolated, thallium resembles tin, but discolors when exposed to air.",
    xpos: 13,
    ypos: 6,
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    atomic_mass: "207.2",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p2",
    summary: "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point. When freshly cut, lead is silvery with a hint of blue; it tarnishes to a dull gray color when exposed to air.",
    xpos: 14,
    ypos: 6,
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomic_mass: "208.980",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p3",
    summary: "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a post-transition metal and one of the p-block elements with chemical properties resembling its lighter group 15 siblings arsenic and antimony.",
    xpos: 15,
    ypos: 6,
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    atomic_mass: "209",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p4",
    summary: "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium, though its metallic character resembles that of its horizontal neighbors in the periodic table: thallium, lead, and bismuth.",
    xpos: 16,
    ypos: 6,
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    atomic_mass: "210",
    category: "metalloid",
    phase: "Solid",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p5",
    summary: "Astatine is a chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements. All of astatine's isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours.",
    xpos: 17,
    ypos: 6,
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomic_mass: "222",
    category: "noble gas",
    phase: "Gas",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p6",
    summary: "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas. It occurs naturally in minute quantities as an intermediate step in the normal radioactive decay chains through which thorium and uranium slowly decay into lead and various other short-lived radioactive elements.",
    xpos: 18,
    ypos: 6,
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    atomic_mass: "223",
    category: "alkali metal",
    phase: "Solid",
    electron_configuration: "[Rn] 7s1",
    summary: "Francium is a chemical element with symbol Fr and atomic number 87. It is extremely radioactive; its most stable isotope, francium-223 (originally called actinium K after the natural decay chain it appears in), has a half-life of only 22 minutes. It is the second-most electronegative element, after caesium, and is the second rarest naturally occurring element (after astatine).",
    xpos: 1,
    ypos: 7,
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    atomic_mass: "226",
    category: "alkaline earth metal",
    phase: "Solid",
    electron_configuration: "[Rn] 7s2",
    summary: "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is silvery-white, but it readily reacts with nitrogen (rather than oxygen) on exposure to air, forming a black surface layer of radium nitride (Ra3N2).",
    xpos: 2,
    ypos: 7,
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    atomic_mass: "227",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 6d1 7s2",
    summary: "Actinium is a chemical element with symbol Ac and atomic number 89. It was first isolated by Friedrich Oskar Giesel in 1902, who gave it the name emanium; the element got its name from Ancient Greek aktis, aktinos (ακτίς, ακτίνος), meaning beam or ray. Actinium gave the name to the actinide series, a group of 15 similar elements between actinium and lawrencium in the periodic table.",
    xpos: 3,
    ypos: 10,
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    atomic_mass: "232.038",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 6d2 7s2",
    summary: "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities as a primordial element (the other being uranium).",
    xpos: 4,
    ypos: 10,
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomic_mass: "231.036",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f2 6d1 7s2",
    summary: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids. It forms various chemical compounds in which protactinium is usually present in the oxidation state +5, but it can also assume +4 and even +3 or +2 states.",
    xpos: 5,
    ypos: 10,
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    atomic_mass: "238.029",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f3 6d1 7s2",
    summary: "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.",
    xpos: 6,
    ypos: 10,
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    atomic_mass: "237",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f4 6d1 7s2",
    summary: "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium named after the planet Uranus led to it being named after Neptune, the next planet out from the Sun.",
    xpos: 7,
    ypos: 10,
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomic_mass: "244",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f6 7s2",
    summary: "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.",
    xpos: 8,
    ypos: 10,
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    atomic_mass: "243",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f7 7s2",
    summary: "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95. This member of the actinide series is located in the periodic table under the lanthanide element europium, and thus by analogy was named after the Americas.",
    xpos: 9,
    ypos: 10,
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    atomic_mass: "247",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f7 6d1 7s2",
    summary: "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie, both known for their research on radioactivity.",
    xpos: 10,
    ypos: 10,
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomic_mass: "247",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f9 7s2",
    summary: "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the University of California Radiation Laboratory where it was discovered in December 1949.",
    xpos: 11,
    ypos: 10,
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    atomic_mass: "251",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f10 7s2",
    summary: "Californium is a radioactive transuranic chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the University of California Radiation Laboratory in Berkeley, by bombarding curium with alpha particles (helium-4 ions).",
    xpos: 12,
    ypos: 10,
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomic_mass: "252",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f11 7s2",
    summary: "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein.",
    xpos: 13,
    ypos: 10,
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    atomic_mass: "257",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f12 7s2",
    summary: "Fermium is a synthetic element with symbol Fm and atomic number 100. It is a transuranic radioactive metal in the actinide series, formed by bombarding thorium with neutrons. It is named after the physicist Enrico Fermi.",
    xpos: 14,
    ypos: 10,
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomic_mass: "258",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f13 7s2",
    summary: "Mendelevium is a synthetic element with symbol Md and atomic number 101. It is a metallic radioactive transuranic element in the actinide series, usually synthesized by bombarding einsteinium with alpha particles.",
    xpos: 15,
    ypos: 10,
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    atomic_mass: "259",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 7s2",
    summary: "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. A radioactive metal, it is the tenth transuranic element and is the penultimate member of the actinide series.",
    xpos: 16,
    ypos: 10,
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomic_mass: "266",
    category: "actinide",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 7s2 7p1",
    summary: "Lawrencium is a synthetic chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements.",
    xpos: 17,
    ypos: 10,
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomic_mass: "267",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d2 7s2",
    summary: "Rutherfordium is a synthetic chemical element with symbol Rf and atomic number 104, named after physicist Ernest Rutherford. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope is 267Rf, which has a half-life of approximately 1.3 hours.",
    xpos: 4,
    ypos: 7,
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    atomic_mass: "268",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d3 7s2",
    summary: "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia (north of Moscow), where it was first produced. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, dubnium-268, has a half-life of approximately 28 hours.",
    xpos: 5,
    ypos: 7,
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomic_mass: "269",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d4 7s2",
    summary: "Seaborgium is a synthetic chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg. As a synthetic element, it can be created in a laboratory but is not found in nature. It is also radioactive; the most stable known isotope, 269Sg, has a half-life of approximately 3.1 minutes.",
    xpos: 6,
    ypos: 7,
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomic_mass: "270",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d5 7s2",
    summary: "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 270Bh, has a half-life of approximately 61 seconds.",
    xpos: 7,
    ypos: 7,
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    atomic_mass: "269",
    category: "transition metal",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d6 7s2",
    summary: "Hassium is a chemical element with symbol Hs and atomic number 108, named after the German state of Hesse. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 269Hs, has a half-life of approximately 9.7 seconds.",
    xpos: 8,
    ypos: 7,
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomic_mass: "278",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d7 7s2",
    summary: "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, meitnerium-278, has a half-life of 7.6 seconds.",
    xpos: 9,
    ypos: 7,
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomic_mass: "281",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d8 7s2",
    summary: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, darmstadtium-281, has a half-life of approximately 10 seconds.",
    xpos: 10,
    ypos: 7,
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomic_mass: "282",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d9 7s2",
    summary: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, roentgenium-282, has a half-life of 2.1 minutes.",
    xpos: 11,
    ypos: 7,
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomic_mass: "285",
    category: "transition metal",
    phase: "Gas",
    electron_configuration: "[Rn] 5f14 6d10 7s2",
    summary: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, copernicium-285, has a half-life of approximately 29 seconds.",
    xpos: 12,
    ypos: 7,
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomic_mass: "286",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p1",
    summary: "Nihonium is a chemical element with symbol Nh and atomic number 113. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, nihonium-286, has a half-life of 20 seconds.",
    xpos: 13,
    ypos: 7,
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomic_mass: "289",
    category: "post-transition metal",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p2",
    summary: "Flerovium is a chemical element with symbol Fl and atomic number 114. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, flerovium-289, has a half-life of approximately 2.6 seconds.",
    xpos: 14,
    ypos: 7,
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomic_mass: "290",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p3",
    summary: "Moscovium is a chemical element with symbol Mc and atomic number 115. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, moscovium-290, has a half-life of 0.8 seconds.",
    xpos: 15,
    ypos: 7,
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomic_mass: "293",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p4",
    summary: "Livermorium is a chemical element with symbol Lv and atomic number 116. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, livermorium-293, has a half-life of approximately 60 milliseconds.",
    xpos: 16,
    ypos: 7,
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomic_mass: "294",
    category: "unknown",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p5",
    summary: "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.",
    xpos: 17,
    ypos: 7,
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomic_mass: "294",
    category: "noble gas",
    phase: "Solid",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p6",
    summary: "Oganesson is a synthetic chemical element with symbol Og and atomic number 118. It was first synthesized in 2002 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia.",
    xpos: 18,
    ypos: 7,
  },
];
